// The SapplyValues statements (https://sapplyvalues.github.io), with German
// translations from political_compass_llm. `effects` says which axis agreeing
// moves and in which direction.
export const STATEMENTS = [
  {
    id: "sapply_000",
    en: "Freedom of business is the best practical way a society can prosper.",
    de: "Unternehmerische Freiheit ist praktisch der beste Weg, wie eine Gesellschaft Wohlstand erreichen kann.",
    effects: { right: 1 },
  },
  {
    id: "sapply_001",
    en: "Charity is a better way of helping those in need than social welfare.",
    de: "Wohltätigkeit ist ein besserer Weg, Bedürftigen zu helfen, als staatliche Sozialhilfe.",
    effects: { right: 1 },
  },
  {
    id: "sapply_002",
    en: "Wages are always fair, as employers know best what a worker's labour is worth.",
    de: "Löhne sind immer fair, da Arbeitgeber am besten wissen, was die Arbeit eines Beschäftigten wert ist.",
    effects: { right: 1 },
  },
  {
    id: "sapply_003",
    en: "It is \"human nature\" to be greedy.",
    de: "Es liegt in der „menschlichen Natur“, gierig zu sein.",
    effects: { right: 1 },
  },
  {
    id: "sapply_004",
    en: "\"Exploitation\" is an outdated term, as the struggles of 1800s capitalism don't exist anymore.",
    de: "„Ausbeutung“ ist ein überholter Begriff, da die Kämpfe des Kapitalismus des 19. Jahrhunderts heute nicht mehr existieren.",
    effects: { right: 1 },
  },
  {
    id: "sapply_005",
    en: "Communism is an ideal that can never work in practice.",
    de: "Kommunismus ist ein Ideal, das in der Praxis niemals funktionieren kann.",
    effects: { right: 1 },
  },
  {
    id: "sapply_006",
    en: "Taxation of the wealthy is a bad idea, society would be better off without it.",
    de: "Die Besteuerung von Wohlhabenden ist eine schlechte Idee; ohne sie wäre die Gesellschaft besser dran.",
    effects: { right: 1 },
  },
  {
    id: "sapply_007",
    en: "The harder you work, the more you progress up the social ladder.",
    de: "Je härter man arbeitet, desto weiter steigt man auf der sozialen Leiter auf.",
    effects: { right: 1 },
  },
  {
    id: "sapply_008",
    en: "Organisations and corporations cannot be trusted and need to be regulated by the government.",
    de: "Organisationen und Unternehmen kann man nicht vertrauen; sie müssen von der Regierung reguliert werden.",
    effects: { right: -1 },
  },
  {
    id: "sapply_009",
    en: "A government that provides for everyone is an inherently good idea.",
    de: "Eine Regierung, die für alle sorgt, ist grundsätzlich eine gute Idee.",
    effects: { right: -1 },
  },
  {
    id: "sapply_010",
    en: "The current welfare system should be expanded to further combat inequality.",
    de: "Das derzeitige Sozialsystem sollte ausgebaut werden, um Ungleichheit weiter zu bekämpfen.",
    effects: { right: -1 },
  },
  {
    id: "sapply_011",
    en: "Land should not be a commodity to be bought and sold.",
    de: "Land sollte keine Ware sein, die gekauft und verkauft wird.",
    effects: { right: -1 },
  },
  {
    id: "sapply_012",
    en: "All industry and the bank should be nationalised.",
    de: "Die gesamte Industrie und die Bank sollten verstaatlicht werden.",
    effects: { right: -1 },
  },
  {
    id: "sapply_013",
    en: "Class is the primary division of society.",
    de: "Klasse ist die grundlegende Spaltung der Gesellschaft.",
    effects: { right: -1 },
  },
  {
    id: "sapply_014",
    en: "Economic inequality is too high in the world.",
    de: "Die wirtschaftliche Ungleichheit in der Welt ist zu hoch.",
    effects: { right: -1 },
  },
  {
    id: "sapply_015",
    en: "Sometimes it is right that the government may spy on its citizens to combat extremists and terrorists.",
    de: "Manchmal ist es richtig, dass die Regierung ihre Bürger ausspionieren darf, um Extremisten und Terroristen zu bekämpfen.",
    effects: { auth: 1 },
  },
  {
    id: "sapply_016",
    en: "Authority figures, if morally correct, are a good thing for society.",
    de: "Autoritätspersonen sind, sofern sie moralisch richtig handeln, gut für die Gesellschaft.",
    effects: { auth: 1 },
  },
  {
    id: "sapply_017",
    en: "Strength is necessary for any government to succeed.",
    de: "Stärke ist notwendig, damit jede Regierung Erfolg haben kann.",
    effects: { auth: 1 },
  },
  {
    id: "sapply_018",
    en: "Only the government can fairly and effectively regulate organisations.",
    de: "Nur die Regierung kann Organisationen fair und wirksam regulieren.",
    effects: { auth: 1 },
  },
  {
    id: "sapply_019",
    en: "Society requires structure and bureaucracy in order to function.",
    de: "Eine Gesellschaft braucht Struktur und Bürokratie, um zu funktionieren.",
    effects: { auth: 1 },
  },
  {
    id: "sapply_020",
    en: "Mandatory IDs should be used to ensure public safety.",
    de: "Verpflichtende Ausweise sollten genutzt werden, um die öffentliche Sicherheit zu gewährleisten.",
    effects: { auth: 1 },
  },
  {
    id: "sapply_021",
    en: "In times of crisis, safety becomes more important than civil liberties.",
    de: "In Krisenzeiten wird Sicherheit wichtiger als bürgerliche Freiheiten.",
    effects: { auth: 1 },
  },
  {
    id: "sapply_022",
    en: "If you have nothing to hide, you have nothing to fear.",
    de: "Wenn man nichts zu verbergen hat, hat man nichts zu befürchten.",
    effects: { auth: 1 },
  },
  {
    id: "sapply_023",
    en: "The government should be less involved in the day to day life of its citizens.",
    de: "Die Regierung sollte weniger in das Alltagsleben ihrer Bürger eingreifen.",
    effects: { auth: -1 },
  },
  {
    id: "sapply_024",
    en: "Without democracy, a society is nothing.",
    de: "Ohne Demokratie ist eine Gesellschaft nichts.",
    effects: { auth: -1 },
  },
  {
    id: "sapply_025",
    en: "Jury nullification should be legal.",
    de: "Die Aufhebung eines Gesetzes durch Geschworene im Einzelfall sollte legal sein.",
    effects: { auth: -1 },
  },
  {
    id: "sapply_026",
    en: "The smaller the government, the freer the people.",
    de: "Je kleiner die Regierung, desto freier die Menschen.",
    effects: { auth: -1 },
  },
  {
    id: "sapply_027",
    en: "The government should, at most, provide emergency services and law enforcement.",
    de: "Die Regierung sollte höchstens Notfalldienste und Strafverfolgung bereitstellen.",
    effects: { auth: -1 },
  },
  {
    id: "sapply_028",
    en: "The police were not created to protect the people, but to uphold the status quo by force.",
    de: "Die Polizei wurde nicht geschaffen, um die Menschen zu schützen, sondern um den Status quo mit Gewalt aufrechtzuerhalten.",
    effects: { auth: -1 },
  },
  {
    id: "sapply_029",
    en: "State schools are a bad idea because our state shouldn't be influencing our children.",
    de: "Staatliche Schulen sind eine schlechte Idee, weil unser Staat unsere Kinder nicht beeinflussen sollte.",
    effects: { auth: -1 },
  },
  {
    id: "sapply_030",
    en: "Two consenting individuals should be able to do whatever they want with each other, even if it makes me uncomfortable.",
    de: "Zwei einwilligende Personen sollten miteinander tun dürfen, was sie wollen, selbst wenn es mir unangenehm ist.",
    effects: { prog: 1 },
  },
  {
    id: "sapply_031",
    en: "An individual's body is their own property, and they should be able to do anything they desire to it.",
    de: "Der Körper eines Individuums ist sein eigenes Eigentum, und es sollte damit tun dürfen, was es möchte.",
    effects: { prog: 1 },
  },
  {
    id: "sapply_032",
    en: "A person should be able to worship whomever or whatever they want.",
    de: "Eine Person sollte verehren dürfen, wen oder was sie will.",
    effects: { prog: 1 },
  },
  {
    id: "sapply_033",
    en: "Nudism is perfectly natural.",
    de: "Nacktheit ist völlig natürlich.",
    effects: { prog: 1 },
  },
  {
    id: "sapply_034",
    en: "Animals deserve certain universal rights.",
    de: "Tiere verdienen bestimmte universelle Rechte.",
    effects: { prog: 1 },
  },
  {
    id: "sapply_035",
    en: "Gender is a social construct, not a natural state of affairs.",
    de: "Geschlecht ist ein soziales Konstrukt, kein natürlicher Zustand der Dinge.",
    effects: { prog: 1 },
  },
  {
    id: "sapply_036",
    en: "Laws based on cultural values, rather than ethical ones, aren't justice.",
    de: "Gesetze, die auf kulturellen Werten statt auf ethischen beruhen, sind keine Gerechtigkeit.",
    effects: { prog: 1 },
  },
  {
    id: "sapply_037",
    en: "Autonomy of body extends even to minors, the mentally ill, and serious criminals.",
    de: "Körperliche Autonomie gilt auch für Minderjährige, psychisch Kranke und schwere Straftäter.",
    effects: { prog: 1 },
  },
  {
    id: "sapply_038",
    en: "Homosexuality is against my values.",
    de: "Homosexualität widerspricht meinen Werten.",
    effects: { prog: -1 },
  },
  {
    id: "sapply_039",
    en: "Transgender individuals should not be able to adopt children.",
    de: "Transgender-Personen sollten keine Kinder adoptieren dürfen.",
    effects: { prog: -1 },
  },
  {
    id: "sapply_040",
    en: "Drugs are harmful and should be banned.",
    de: "Drogen sind schädlich und sollten verboten werden.",
    effects: { prog: -1 },
  },
  {
    id: "sapply_041",
    en: "The death penalty should exist for certain crimes.",
    de: "Für bestimmte Verbrechen sollte es die Todesstrafe geben.",
    effects: { prog: -1 },
  },
  {
    id: "sapply_042",
    en: "Victimless crimes should still be punished.",
    de: "Opferlose Verbrechen sollten dennoch bestraft werden.",
    effects: { prog: -1 },
  },
  {
    id: "sapply_043",
    en: "One cannot be moral without religion.",
    de: "Ohne Religion kann man nicht moralisch sein.",
    effects: { prog: -1 },
  },
  {
    id: "sapply_044",
    en: "Parents should hold absolute power over their children, as they are older and more experienced.",
    de: "Eltern sollten absolute Macht über ihre Kinder haben, da sie älter und erfahrener sind.",
    effects: { prog: -1 },
  },
  {
    id: "sapply_045",
    en: "Multiculturalism is bad.",
    de: "Multikulturalismus ist schlecht.",
    effects: { prog: -1 },
  },
];
