// Every visible string. Levels are in the order of the answer scale in
// reading.js; Jev always judges against the English wording.
export const STRINGS = {
  en: {
    title: 'Political Compass 2.0',
    hint: 'Answer in your own words, as long or short as you like. Jev reads all your answers at the end.',
    placeholder: 'What do you think?',
    back: 'Back',
    skip: 'Skip',
    next: 'Next',
    finish: 'See where you stand',
    finishEarly: 'Finish now',
    reading: 'Jev is reading your answers…',
    keyPrompt: 'This page needs an OpenRouter key to ask Jev. It stays in this browser.',
    keySave: 'Use key',
    retry: 'Try again',
    failed: 'Jev could not read your answers',
    edit: 'Change answers',
    restart: 'Start over',
    restartConfirm: 'Delete all your answers?',
    privacy: 'Your answers are sent to OpenRouter and TypeSafe to be read. Nothing else is stored anywhere but this browser.',
    counted: (n, total) => `Based on ${n} of ${total} statements.`,
    left: 'Left',
    right: 'Right',
    auth: 'Authoritarian',
    lib: 'Libertarian',
    conservative: 'Conservative',
    progressive: 'Progressive',
    axisNames: { right: 'Economic', auth: 'Authority', prog: 'Social' },
    noAnswers: 'Answer at least one statement first.',
    certainty: (p) => `${Math.round(p * 100)}% sure`,
    levels: ['Strongly disagree', 'Disagree', 'Neutral or unsure', 'Agree', 'Strongly agree'],
  },
  de: {
    title: 'Politischer Kompass 2.0',
    hint: 'Antworte in deinen eigenen Worten, so kurz oder lang du magst. Jev liest am Ende alle Antworten.',
    placeholder: 'Was denkst du?',
    back: 'Zurück',
    skip: 'Überspringen',
    next: 'Weiter',
    finish: 'Zeig mir, wo ich stehe',
    finishEarly: 'Jetzt auswerten',
    reading: 'Jev liest deine Antworten…',
    keyPrompt: 'Diese Seite braucht einen OpenRouter-Schlüssel, um Jev zu fragen. Er bleibt in diesem Browser.',
    keySave: 'Schlüssel verwenden',
    retry: 'Nochmal versuchen',
    failed: 'Jev konnte deine Antworten nicht lesen',
    edit: 'Antworten ändern',
    restart: 'Neu anfangen',
    restartConfirm: 'Alle Antworten löschen?',
    privacy: 'Deine Antworten werden zum Lesen an OpenRouter und TypeSafe geschickt. Gespeichert wird nur in diesem Browser.',
    counted: (n, total) => `Basierend auf ${n} von ${total} Aussagen.`,
    left: 'Links',
    right: 'Rechts',
    auth: 'Autoritär',
    lib: 'Libertär',
    conservative: 'Konservativ',
    progressive: 'Progressiv',
    axisNames: { right: 'Wirtschaft', auth: 'Autorität', prog: 'Gesellschaft' },
    noAnswers: 'Beantworte zuerst mindestens eine Aussage.',
    certainty: (p) => `${Math.round(p * 100)} % sicher`,
    levels: ['Stimme überhaupt nicht zu', 'Stimme nicht zu', 'Neutral oder unsicher', 'Stimme zu', 'Stimme voll zu'],
  },
};

export function pickLanguage(saved, browserLanguage) {
  if (saved in STRINGS) return saved;
  return browserLanguage?.toLowerCase().startsWith('de') ? 'de' : 'en';
}
