// Topic suggestions from the original VotingAid, each with the start of an
// opinion so people know what kind of sentence is expected.
export const SUGGESTIONS = {
  'Unterstützung der Ukraine': 'Die Ukraine soll…',
  'Erneuerbare Energien': 'Erneuerbare Energien sollen…',
  Bürgergeld: 'Das Bürgergeld soll…',
  'Tempolimit auf Autobahnen': 'Ein Tempolimit auf Autobahnen soll…',
  Asyl: 'Asylsuchende sollen…',
  Mietpreisbremse: 'Die Mietpreisbremse soll…',
  Videoüberwachung: 'Die Videoüberwachung an öffentlichen Orten soll…',
  Rente: 'Die Rente soll…',
  'Fachkräfte aus dem Ausland': 'Fachkräfte…',
  Atomkraft: 'Die Atomkraft soll…',
  'Bund und Bildung': 'Der Bund soll in der Bildung…',
  'Rüstungsexporte in Krisengebiete': 'Rüstungsexporte sollen…',
  Frauenquote: 'Die Frauenquote soll…',
  'Ökologische Landwirtschaft': 'Die Landwirtschaft soll…',
  'AfD-Verbot': 'Die AfD soll…',
  Lieferkettengesetz: 'Das Lieferkettengesetz soll…',
  BAföG: 'Das BAföG soll…',
  Schuldenbremse: 'Die Schuldenbremse soll…',
  Klimaziele: 'Die Klimaziele sollen…',
  Kohleausstieg: 'Der Kohleausstieg soll…',
  Schwangerschaftsabbruch: 'Der Schwangerschaftsabbruch soll…',
  Euro: 'Der Euro soll…',
  Verkehrswende: 'Die Verkehrswende soll…',
  Volksentscheide: 'Volksentscheide sollen…',
  'Strafrecht für unter 14-Jährige': 'Das Strafrecht für…',
  Zölle: 'Zölle sollen…',
  Heizungen: 'Heizungen sollen…',
  Mindestlohn: 'Der Mindestlohn soll…',
  Verteidigungsausgaben: 'Die Verteidigungsausgaben sollen…',
  Entwicklungszusammenarbeit: 'Die Entwicklungszusammenarbeit soll…',
  'Großspenden an Parteien': 'Großspenden an Parteien sollen…',
  Verbrennungsmotoren: 'Verbrennungsmotoren sollen…',
  Vermögensteuer: 'Die Vermögensteuer soll…',
  Unternehmensteuern: 'Die Unternehmensteuern sollen…',
  Einkommensteuer: 'Die Einkommensteuer soll…',
  Mehrwertsteuer: 'Die Mehrwertsteuer soll…',
  Rundfunkbeitrag: 'Der Rundfunkbeitrag soll…',
  Cannabis: 'Cannabis soll…',
  'Doppelte Staatsbürgerschaft': 'Die doppelte Staatsbürgerschaft soll…',
  'CO2-Preis': 'Der CO2-Preis soll…',
  Digitalisierung: 'Die Digitalisierung soll…',
  'Künstliche Intelligenz': 'Der Einsatz von Künstlicher Intelligenz soll…',
  'Gesundheit und Pflege': 'Das Gesundheitssystem…',
  'Innere Sicherheit': 'Die innere Sicherheit…',
  Cyberkriminalität: 'Cyberkriminalität…',
  'Infrastruktur und Verkehr': 'Die Verkehrsinfrastruktur…',
  'Europäische Union': 'Die Europäische Union…',
};
