// Topics for "Thema vorschlagen": federal issues the parties disagree on, as of
// 2026-09. Only the topic; people write what should happen in their own words.
export const SUGGESTIONS = [
  'Grundsicherungsgeld',
  'Mindestlohn',
  'Arbeitszeit',
  'Rente',
  'Gesetzliche Krankenversicherung',
  'Pflegeversicherung',
  'BAföG',
  'Mietpreisbremse',
  'Sozialer Wohnungsbau',
  'Schuldenbremse',
  'Vermögensteuer',
  'Erbschaftsteuer',
  'Unternehmensteuern',
  'Einkommensteuer',
  'Mehrwertsteuer',
  'Zölle',
  'Lieferkettengesetz',
  'Erneuerbare Energien',
  'Energiepreise',
  'Atomkraft',
  'Klimaziele',
  'CO2-Preis',
  'Kohleausstieg',
  'Heizungen',
  'Klimaanpassung',
  'Ökologische Landwirtschaft',
  'Verbrennungsmotoren',
  'Tempolimit auf Autobahnen',
  'Deutschlandticket',
  'Bahninfrastruktur',
  'Asyl',
  'Grenzkontrollen',
  'Familiennachzug',
  'Fachkräfte aus dem Ausland',
  'Einbürgerung',
  'Unterstützung der Ukraine',
  'Russland-Sanktionen',
  'Verteidigungsausgaben',
  'Wehrpflicht',
  'Rüstungsexporte in Krisengebiete',
  'Entwicklungszusammenarbeit',
  'Videoüberwachung',
  'Vorratsdatenspeicherung',
  'AfD-Verbot',
  'Schwangerschaftsabbruch',
  'Cannabis',
  'Selbstbestimmungsgesetz',
  'Künstliche Intelligenz',
  'Digitale Verwaltung',
  'Bildungsfinanzierung des Bundes',
  'Großspenden an Parteien',
];
